[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
dextra = "EkDU4dizCrRyaNfRfTcsHFH4rTmeBP4PQBkH74Ua3RvD"
governance = "Governance111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ANCHOR_PROVIDER_URL=http://127.0.0.1:8899 ANCHOR_WALLET=~/.config/solana/id.json npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[idl]
out = "target/idl"

[typescript]
out = "target/types"

[test]
startup_wait = 5000
validator = { url = "http://127.0.0.1:8899", faucet = "http://127.0.0.1:8081" }
