[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
freelance = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[idl]
out = "target/idl"

[typescript]
out = "target/types"

[test]
startup_wait = 5000
validator = { url = "http://localhost:8898" }
