[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
freelance = "BhL4V5qTP33T3PyjRZbqh1ALSBmkoMMFGLv4Whrf315S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8898"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[idl]
out = "target/idl"

[typescript]
out = "target/types"

[test]
startup_wait = 5000
validator = { url = "http://127.0.0.1:8898", faucet = "http://127.0.0.1:8081" }
