[toolchain]
anchor_version = "0.30.1"
[features]
resolution = true
skip-lint = false

[programs.localnet]
freelance = "CTGXUcNqUUzQpXd53yo5GSj5a2DBoFq4LHruQbgwUpvQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[idl]
out = "target/idl"

[typescript]
out = "target/types"
